HID: ft260: fix a NULL pointer dereference in ft260_i2c_write
The len=0 passed into the ft260_i2c_write() triggered the NULL
pointer dereference in the debug message on access to data[0].
Since a Write without data makes little sense in this context,
do not allow it.

Before:

$ sudo i2ctransfer -y 13 w0@0x51
Killed

After:

$ sudo i2ctransfer -y 13 w0@0x51
Error: Sending messages failed: Invalid argument

Reported-by: Enrik Berkhan <Enrik.Berkhan@inka.de>
Signed-off-by: Michael Zaidman <michael.zaidman@gmail.com>